### DISCUSSION TITLE
Markdown formatting of shortname

### DISCUSSION THREAD

**Discussion by ericpace** [rchaput/acronyms#28] [Q&A]
Can't really figure out how I can format the shortname. I would like to include a subscript, e.g. as follows:

```yaml
acronyms:
  keys:
    - shortname: x~y~
      longname: x with y subscripted
```

I've tried to wrap the shortname in single quotes and backticks, but this did not help. 

Thanks
