### DISCUSSION TITLE
suggestion:  simplified format for input using "fromfile"

### DISCUSSION THREAD

**Discussion by bergsmat** [rchaput/acronyms#33] [Ideas]
@rchaput and team, thanks for this essential tool.  It is a game-changer for me.

Would you consider supporting a simplified syntax for acronyms, at least under the "fromfile" option?

For instance, the current structure is like this:

```
---
acronyms:
  keys:
  - shortname: qmd
    longname: Quarto documents
  - shortname: YAML
    longname: YAML Ain't Markup Language
---
```

which could be expressed more succinctly as this:

```
qmd: Quarto documents
YAML: YAML Ain't Markup Language
```

Then we could write a function that reads either (as a file): 
```
get_acronyms <- function(x, ...){
  stopifnot(file.exists(x))
  y <- yaml::yaml.load_file(x)
  if(names(y)[[1]] == 'acronyms'){
    if(names(y[[1]]) == 'keys'){
      return(y)
    }
  }
  acr <- lapply(
    seq_along(y), 
    function(i)list(
      shortname = names(y)[[i]], 
      longname = y[[i]]
    )
  )
  z <- list(acronyms = list(keys = acr))
  return(z)
}
```

and returns the conventional data structure:

```
$acronyms
$acronyms$keys
$acronyms$keys[[1]]
$acronyms$keys[[1]]$shortname
[1] "qmd"

$acronyms$keys[[1]]$longname
[1] "Quarto documents"


$acronyms$keys[[2]]
$acronyms$keys[[2]]$shortname
[1] "YAML"

$acronyms$keys[[2]]$longname
[1] "YAML Ain't Markup Language"
```

I find the short form easy to write and easy to explain. In fact, It looks a lot like the LoA as rendered! Very possible I'm missing some operational constraint.

**Comment by rchaput** [comment]
Thanks for the compliment!

I love this idea, it would be really shorter and clearer to write.

I think that the only thing missing is that, with the actual format, we can specify the key if necessary:

```yaml
acronyms:
  keys:
    - key: something
      shortname: Something that cannot/should not be used as a key for some reason but we still want as a shortname
      longname: Longname
```

But I do not think anyone uses this feature anyway. And they could still resort to the longer format if they need it.

Can you create a PR with your code, ideally with a quick test to ensure that it works? I can create the test if you're not sure.
