### ISSUE TITLE
List of Acronyms one single page

### ISSUE THREAD

**Issue by espinielli** [rchaput/acronyms#11]
I am using this extension for a Quarto website and when I insert the following configuration in the `_quarto.yml`

```yml
filters:
  - acronyms
acronyms:
  loa_title: "List of Acronyms"
  include_unused: false
  insert_loa: "end"
  insert_links: true
  id_prefix: "acronyms_"
  sorting: "alphabetical"
  non_existing: "key"
  style: "long-short"
  fromfile:
    - media/acronyms.yml

```
 I get a "List of Acronyms" for every `.qmd` file.
I reduced the issue by adding the above config only on the pages needing it, but I would like to know whether it would be possible to further reduce the "List of Acronyms" sections by just having one single page for all acronyms used in the website.
Just asking...
Thanks a lot in advance!

**Comment by rchaput** [comment]
The problem is that Quarto renders each document independently, so the **acronyms** extension does not even know that you are building a website with several pages. For each page, **acronyms** is called with a "fresh state".

One way to reduce the problem would be to:

- Print the List of Acronyms only on a dedicated page

```yaml
filters:
  - acronyms
acronyms:
  include_unused: true
  insert_loa: "end"
  loa_title: "List of Acronyms"
  sorting: "alphabetical"
  fromfile:
    - media/acronyms.yml
```

Note the `include_unused: true`, because on this specific page, no acronym will be considered "used" (they do not appear anywhere), so we must force them to be printed in the LoA anyway.

- Then, on each page, disable the List of Acronyms and the links:

```yaml
filters:
  - acronyms
acronyms:
  insert_loa: false
  insert_links: false
  non_existing: "key"
  style: "long-short"
  fromfile:
    - media/acronyms.yml
```

Unfortunately, we must disable the links because **acronyms** would not know that the LoA exists on a different page, and I am pretty sure the link would not work between different pages.
Again, this is due to Quarto rendering each document separately.

To solve this, I would need to tap into Quarto's cross-section references mechanism, and I am not sure how it works.
