### ISSUE TITLE
Error when rendering my document

### ISSUE THREAD

**Issue by Pierre9344** [rchaput/acronyms#12]
Hello,

I just discovered this plugin and I tried to add it in my document but I get the error next:
```
Error running filter C:/Users/E142543N/AppData/Local/Programs/Quarto/share/filters/main.lua:
...HESE\MANUSCRIT\_extensions\rchaput\acronyms\acronyms.lua:34: An Acronym shortname should not be nil!
stack traceback:
	...HESE\MANUSCRIT\_extensions\rchaput\acronyms\acronyms.lua:34: in method 'new'
	...HESE\MANUSCRIT\_extensions\rchaput\acronyms\acronyms.lua:151: in function 'acronyms.parseFromMetadata'
	...ANUSCRIT\_extensions\rchaput\acronyms\parse-acronyms.lua:54: in function <...ANUSCRIT\_extensions\rchaput\acronyms\parse-acronyms.lua:50>
	[C]: in ?
	[C]: in method 'walk'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:150: in local 'checked_walk'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:202: in function 'run_emulated_filter'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:788: in local 'callback'
	[string "..."]:1883: in field 'withScriptFile'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:800: in upvalue 'run_emulated_filter_chain'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:837: in function <...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:834>
stack traceback:
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:150: in local 'checked_walk'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:202: in function 'run_emulated_filter'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:788: in local 'callback'
	[string "..."]:1883: in field 'withScriptFile'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:800: in upvalue 'run_emulated_filter_chain'
	...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:837: in function <...43N/AppData/Local/Programs/Quarto/share/filters/main.lua:834>
````

The acronyms I added where:

```
filters:
  - acronyms

acronyms:
  keys:
    - shorname: "ARNt"
      longname: "ARN de transferts"
    - shorname: "miARN"
      longname: "micro-ARN"
    - shortname: "SCZ"
      longname: "Schizophrenie"
    - shortname: "TB"
      longname: "Troubles Bipolaires"
    - shortnames: "DM"
      longname: "Depression Majeure"
    - shortname: "ARNm"
      longname: "ARN messager"
    - shorname: "ARNnc"
      longname: "ARN non-codants"
    - shorname: "ENCODE"
      longname: "Encyclopédie des éléments de l'ADN"
    - shorname: "PBMC"
      longname: "Cellules Mononucléaires du Sang Périphérique"
    - shorname: "SI"
      longname: "Système Immunitaire"
    - shorname: "SNP"
      longname: "Polymorphisme d'un seul Nucléotide"
```

I'm using quarto 1.4.424 on windows 11. Is the 1.4 version supported by the filters?
