### ISSUE TITLE
LoA with the new shortcode style

### ISSUE THREAD

**Issue by agdamsbo** [rchaput/acronyms#27]
Hi
So, I have run into an issue. I wanted to migrate to the new shortcode style `{{< acr KEY >}}`. When doing so, the LoA is empty (using the option `include_unused: true`). Mixing new and old style shortcode, `\acr{KEY}` is included in the LoA.

**Comment by agdamsbo** [comment]
And here is the example to replicate:

```
---
title: Alphabetical glossary
format: pdf
editor: source
filters:
  - acronyms
acronyms:
  sorting: "alphabetical"
  include_unused: false
  keys:
    - shortname: Qt
      longname: Quarto
    - shortname: iQt
      longname: inside-Quarto
    - shortname: aA
      longname: alphabetically
    - shortname: H
      longname: handle
---

This \acr{Qt} extension adds the ability to automatically \acr{H} acronyms {{< acr iQt >}}. Would love to be able to sort \acr{aA}, independent of letter size.
```
