### ISSUE TITLE
option to sort alphabetically and ignore letter case

### ISSUE THREAD

**Issue by agdamsbo** [rchaput/acronyms#4]
Hi. This is a great extension!

I am using the extension as part of a report. I want to sort acronyms/glossaries and ignore if the start letter is capital or not. Is this possible?

Below is a try at illustrating the case:

```
---
title: Alphabetical glossary
format: pdf
editor: source
filters:
  - acronyms
acronyms:
  sorting: "alphabetical"
  keys:
    - shortname: Qt
      longname: Quarto
    - shortname: iQt
      longname: inside-Quarto
    - shortname: aA
      longname: alphabetically
    - shortname: H
      longname: handle
---

This \acr{Qt} extension adds the ability to automatically \acr{handle} 
 \acr{iQt} acronyms.
Would love to be able to sort \acr{aA}, independent of letter size.
```

The desired output would be to have to loa order like this:
aA
H
iQt
Qt

but the current sorting order is the following:
H
Qt
aA
iQt

Makes sense? Presume it's something with the lua sorting, that I don't get?
